-- 관리자 테이블 (ADM)

DROP TABLE ADMIN_TB CASCADE CONSTRAINTS;
CREATE TABLE ADMIN_TB (
    ADM_NO  NCHAR(8),       -- PK
    ADM_PW  NVARCHAR2(500)  NOT NULL
);

ALTER TABLE ADMIN_TB ADD CONSTRAINT PK_ADM_TB PRIMARY KEY(ADM_NO);

DROP SYNONYM ADM;
CREATE SYNONYM ADM FOR ADMIN_TB;


-- 난수 테이블 (RND)

DROP TABLE RANDOM_TB CASCADE CONSTRAINTS;
CREATE TABLE RANDOM_TB (
    RND_EMAIL   NVARCHAR2(50),  -- PK
    RND_CODE    NCHAR(6),       -- PK
    RND_TYPE    NCHAR(1),       -- CHECK('B', 'P')
    RND_DATE    DATE            DEFAULT SYSDATE
);

ALTER TABLE RANDOM_TB ADD CONSTRAINT PK_RND_TB PRIMARY KEY(RND_EMAIL, RND_CODE);
ALTER TABLE RANDOM_TB ADD CONSTRAINT CH_RND_TYPE CHECK(RND_TYPE IN('B', 'P'));

DROP SYNONYM RND;
CREATE SYNONYM RND FOR RANDOM_TB;


-- 개인 회원 테이블 (PER)

DROP TABLE PERSONAL_TB CASCADE CONSTRAINTS;
CREATE TABLE PERSONAL_TB (
    PER_NO      NCHAR(8),       -- PK
    PER_EMAIL   NVARCHAR2(50)   NOT NULL,       -- UNIQUE
    PER_PW      NVARCHAR2(500)  NOT NULL,
    PER_NAME    NVARCHAR2(20)   NOT NULL,
    PER_PHONE   NVARCHAR2(13)   NOT NULL,
    PER_PHOTO   NVARCHAR2(1000) DEFAULT 'user.png',
    PER_LOC     NVARCHAR2(1000) DEFAULT 'resources/images/defaultProfile/',
    PER_EMCHK   NCHAR(1)        DEFAULT 'X',    -- CHECK('O', 'X')
    PER_LEAVE   NCHAR(1)        DEFAULT 'X',    -- CHECK('O', 'X')
    PER_LTIME   DATE
);

ALTER TABLE PERSONAL_TB ADD CONSTRAINT PK_PER_TB PRIMARY KEY(PER_NO);
ALTER TABLE PERSONAL_TB ADD CONSTRAINT UQ_PER_EMAIL UNIQUE(PER_EMAIL);
ALTER TABLE PERSONAL_TB ADD CONSTRAINT CH_PER_EMCHK CHECK(PER_EMCHK IN('O', 'X'));
ALTER TABLE PERSONAL_TB ADD CONSTRAINT CH_PER_LEAVE CHECK(PER_LEAVE IN('O', 'X'));

DROP SYNONYM PER;
CREATE SYNONYM PER FOR PERSONAL_TB;

DROP SEQUENCE PER_SEQ;
CREATE SEQUENCE PER_SEQ START WITH 1000001 INCREMENT BY 1 MAXVALUE 9999999;


-- 동물 종류 테이블 (PTY)

DROP TABLE PET_TYPE_TB CASCADE CONSTRAINTS;
CREATE TABLE PET_TYPE_TB (
    PTY_NO      NUMBER(2, 0),   -- PK
    PTY_NAME    NVARCHAR2(20)   NOT NULL    -- UNIQUE
);

ALTER TABLE PET_TYPE_TB ADD CONSTRAINT PK_PTY_TB PRIMARY KEY(PTY_NO);
ALTER TABLE PET_TYPE_TB ADD CONSTRAINT UQ_PTY_NAME UNIQUE(PTY_NAME);

DROP SYNONYM PTY;
CREATE SYNONYM PTY FOR PET_TYPE_TB;

DROP SEQUENCE PTY_SEQ;
CREATE SEQUENCE PTY_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE 99;

INSERT INTO PTY VALUES(PTY_SEQ.NEXTVAL, '소형견');
INSERT INTO PTY VALUES(PTY_SEQ.NEXTVAL, '중형견');
INSERT INTO PTY VALUES(PTY_SEQ.NEXTVAL, '대형견');
INSERT INTO PTY VALUES(PTY_SEQ.NEXTVAL, '고양이');
INSERT INTO PTY VALUES(PTY_SEQ.NEXTVAL, '소동물');
INSERT INTO PTY VALUES(PTY_SEQ.NEXTVAL, '햄스터');
INSERT INTO PTY VALUES(PTY_SEQ.NEXTVAL, '고슴도치');
INSERT INTO PTY VALUES(PTY_SEQ.NEXTVAL, '페럿');
INSERT INTO PTY VALUES(PTY_SEQ.NEXTVAL, '기니피그');
INSERT INTO PTY VALUES(PTY_SEQ.NEXTVAL, '파충류');
INSERT INTO PTY VALUES(PTY_SEQ.NEXTVAL, '조류');
INSERT INTO PTY VALUES(PTY_SEQ.NEXTVAL, '가축');
INSERT INTO PTY VALUES(PTY_SEQ.NEXTVAL, '기타');


-- 동물 테이블 (PET)

DROP TABLE PET_TB CASCADE CONSTRAINTS;
CREATE TABLE PET_TB (
    PET_NO      NCHAR(8),       -- PK
    PER_NO      NCHAR(8),       -- FK
    PTY_NO      NUMBER(2, 0),   -- FK
    PET_VRT     NVARCHAR2(20)   NOT NULL,
    PET_NAME    NVARCHAR2(10)   NOT NULL,
    PET_AGE     NCHAR(4)        NOT NULL,
    PET_SEX     NCHAR(1),       -- CHECK('F', 'M')
    PET_NTR     NCHAR(1),       -- CHECK('O', 'X')
    PET_PHOTO   NVARCHAR2(1000) DEFAULT 'pet.png',
    PET_LOC     NVARCHAR2(1000) DEFAULT 'resources/images/defaultProfile/'
);

ALTER TABLE PET_TB ADD CONSTRAINT PK_PET_TB PRIMARY KEY(PET_NO);
ALTER TABLE PET_TB ADD CONSTRAINT FK_PET_PER_NO FOREIGN KEY(PER_NO) REFERENCES PERSONAL_TB(PER_NO);
ALTER TABLE PET_TB ADD CONSTRAINT FK_PET_PTY_NO FOREIGN KEY(PTY_NO) REFERENCES PET_TYPE_TB(PTY_NO);
ALTER TABLE PET_TB ADD CONSTRAINT CH_PET_SEX CHECK(PET_SEX IN ('F', 'M'));
ALTER TABLE PET_TB ADD CONSTRAINT CH_PET_NTR CHECK(PET_NTR IN ('O', 'X'));

DROP SYNONYM PET;
CREATE SYNONYM PET FOR PET_TB;

DROP SEQUENCE PET_SEQ;
CREATE SEQUENCE PET_SEQ START WITH 1000001 INCREMENT BY 1 MAXVALUE 9999999;


-- 동물 컬럼 테이블 (PCL)

DROP TABLE PET_COLUMN_TB CASCADE CONSTRAINTS;
CREATE TABLE PET_COLUMN_TB (
    PCL_NO      NUMBER(2, 0),   -- PK
    PCL_NAME    NVARCHAR2(20)   NOT NULL    -- UNIQUE
);

ALTER TABLE PET_COLUMN_TB ADD CONSTRAINT PK_PCL_TB PRIMARY KEY(PCL_NO);
ALTER TABLE PET_COLUMN_TB ADD CONSTRAINT UQ_PCL_NAME UNIQUE(PCL_NAME);

DROP SYNONYM PCL;
CREATE SYNONYM PCL FOR PET_COLUMN_TB;

DROP SEQUENCE PCL_SEQ;
CREATE SEQUENCE PCL_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE 99;

INSERT INTO PCL VALUES(PCL_SEQ.NEXTVAL, '몸무게');
INSERT INTO PCL VALUES(PCL_SEQ.NEXTVAL, '질병');
INSERT INTO PCL VALUES(PCL_SEQ.NEXTVAL, '만난 날');
INSERT INTO PCL VALUES(PCL_SEQ.NEXTVAL, '주의해야 할 음식');
INSERT INTO PCL VALUES(PCL_SEQ.NEXTVAL, '식사 횟수 및 배급량');
INSERT INTO PCL VALUES(PCL_SEQ.NEXTVAL, '배변 훈련');
INSERT INTO PCL VALUES(PCL_SEQ.NEXTVAL, '특이사항');


-- 동물 상세 테이블 (PDT)

DROP TABLE PET_DETAIL_TB CASCADE CONSTRAINTS;
CREATE TABLE PET_DETAIL_TB (
    PET_NO  NCHAR(8),       -- PK, FK
    PCL_NO  NUMBER(2, 0),   -- PK, FK
    PDT_CTT NVARCHAR2(500)  NOT NULL
);

ALTER TABLE PET_DETAIL_TB ADD CONSTRAINT FK_PDT_PET_NO FOREIGN KEY(PET_NO) REFERENCES PET_TB(PET_NO);
ALTER TABLE PET_DETAIL_TB ADD CONSTRAINT FK_PDT_PCL_NO FOREIGN KEY(PCL_NO) REFERENCES PET_COLUMN_TB(PCL_NO);
ALTER TABLE PET_DETAIL_TB ADD CONSTRAINT PK_PDT_TB PRIMARY KEY(PET_NO, PCL_NO);

DROP SYNONYM PDT;
CREATE SYNONYM PDT FOR PET_DETAIL_TB;


-- 기업 회원 테이블 (BUS)

DROP TABLE BUSINESS_TB CASCADE CONSTRAINTS;
CREATE TABLE BUSINESS_TB (
    BUS_NO      NCHAR(8),       -- PK
    BUS_EMAIL   NVARCHAR2(40)   NOT NULL,       -- UNIQUE
    BUS_PW      NVARCHAR2(100)  NOT NULL,
    BUS_NAME    NVARCHAR2(20)   NOT NULL,
    BUS_CEO     NVARCHAR2(20)   NOT NULL,
    BUS_LCNO    NVARCHAR2(12)   NOT NULL,       -- UNIQUE
    BUS_PHONE   NVARCHAR2(13)   NOT NULL,
    BUS_POST    NVARCHAR2(6)    NOT NULL,
    BUS_ADDR    NVARCHAR2(300)  NOT NULL,
    BUS_ADDR2   NVARCHAR2(300)  NOT NULL,
    BUS_EMCHK   NCHAR(1)        DEFAULT 'X',    -- CHECK('O', 'X')
    BUS_CHK     NCHAR(1)        DEFAULT 'X',    -- CHECK('O', 'X')
    BUS_TIME    DATE            DEFAULT SYSDATE,
    BUS_LEAVE   NCHAR(1)        DEFAULT 'X',    -- CHECK('O', 'X')
    BUS_LTIME   DATE
);

ALTER TABLE BUSINESS_TB ADD CONSTRAINT PK_BUS_TB PRIMARY KEY(BUS_NO);
ALTER TABLE BUSINESS_TB ADD CONSTRAINT UQ_BUS_EMAIL UNIQUE(BUS_EMAIL);
ALTER TABLE BUSINESS_TB ADD CONSTRAINT UQ_BUS_LCNO UNIQUE(BUS_LCNO);
ALTER TABLE BUSINESS_TB ADD CONSTRAINT CH_BUS_EMCHK CHECK(BUS_EMCHK IN ('O', 'X'));
ALTER TABLE BUSINESS_TB ADD CONSTRAINT CH_BUS_CHK CHECK(BUS_CHK IN ('O', 'X'));
ALTER TABLE BUSINESS_TB ADD CONSTRAINT CH_BUS_LEAVE CHECK(BUS_LEAVE IN ('O', 'X'));

DROP SYNONYM BUS;
CREATE SYNONYM BUS FOR BUSINESS_TB;

DROP SEQUENCE BUS_SEQ;
CREATE SEQUENCE BUS_SEQ START WITH 1000001 INCREMENT BY 1 MAXVALUE 9999999;


-- 업종 테이블 (BCT)

DROP TABLE BUS_CATEGORY_TB CASCADE CONSTRAINTS;
CREATE TABLE BUS_CATEGORY_TB (
    BCT_CODE    NCHAR(1),       -- PK
    BCT_NAME    NVARCHAR2(10)   NOT NULL    -- UNIQUE
);

ALTER TABLE BUS_CATEGORY_TB ADD CONSTRAINT PK_BCT_TB PRIMARY KEY(BCT_CODE);
ALTER TABLE BUS_CATEGORY_TB ADD CONSTRAINT UQ_BCT_NAME UNIQUE(BCT_NAME);

DROP SYNONYM BCT;
CREATE SYNONYM BCT FOR BUS_CATEGORY_TB;

INSERT INTO BCT VALUES('M', '병원');
INSERT INTO BCT VALUES('B', '미용');
INSERT INTO BCT VALUES('H', '호텔');


-- 사진 종류 테이블 (GCT)

DROP TABLE GLR_CATEGORY_TB CASCADE CONSTRAINTS;
CREATE TABLE GLR_CATEGORY_TB (
    GCT_NO      NUMBER(2, 0),   -- PK
    GCT_NAME    NVARCHAR2(10)   NOT NULL    -- UNIQUE
);

ALTER TABLE GLR_CATEGORY_TB ADD CONSTRAINT PK_GCT_TB PRIMARY KEY(GCT_NO);
ALTER TABLE GLR_CATEGORY_TB ADD CONSTRAINT UQ_GCT_NAME UNIQUE(GCT_NAME);

DROP SYNONYM GCT;
CREATE SYNONYM GCT FOR GLR_CATEGORY_TB;

DROP SEQUENCE GCT_SEQ;
CREATE SEQUENCE GCT_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE 99;

INSERT INTO GCT VALUES(GCT_SEQ.NEXTVAL, '사업자등록증');
INSERT INTO GCT VALUES(GCT_SEQ.NEXTVAL, '기업대표사진');
INSERT INTO GCT VALUES(GCT_SEQ.NEXTVAL, '기업갤러리');


-- 사진 테이블 (GLR)

DROP TABLE GALLERY_TB CASCADE CONSTRAINTS;
CREATE TABLE GALLERY_TB (
    BUS_NO      NCHAR(8),           -- PK, FK
    BCT_CODE    NCHAR(1),           -- PK, FK
    GCT_NO      NUMBER(2, 0),       -- PK, FK
    GLR_FILE    NVARCHAR2(1000),    -- PK
    GLR_LOC     NVARCHAR2(1000)     NOT NULL
);

ALTER TABLE GALLERY_TB ADD CONSTRAINT FK_GLR_BUS_NO FOREIGN KEY(BUS_NO) REFERENCES BUSINESS_TB(BUS_NO);
ALTER TABLE GALLERY_TB ADD CONSTRAINT FK_GLR_BCT_CODE FOREIGN KEY(BCT_CODE) REFERENCES BUS_CATEGORY_TB(BCT_CODE);
ALTER TABLE GALLERY_TB ADD CONSTRAINT FK_GLR_GCT_NO FOREIGN KEY(GCT_NO) REFERENCES GLR_CATEGORY_TB(GCT_NO);
ALTER TABLE GALLERY_TB ADD CONSTRAINT PK_GLR_TB PRIMARY KEY(BUS_NO, BCT_CODE, GCT_NO, GLR_FILE);

DROP SYNONYM GLR;
CREATE SYNONYM GLR FOR GALLERY_TB;


-- 서비스 테이블 (SVC)

DROP TABLE SERVICE_TB CASCADE CONSTRAINTS;
CREATE TABLE SERVICE_TB (
    BUS_NO      NCHAR(8),       -- PK, FK
    BCT_CODE    NCHAR(1),       -- PK, FK
    SVC_PRI     NUMBER(1, 0)    NOT NULL
);

ALTER TABLE SERVICE_TB ADD CONSTRAINT FK_SVC_BUS_NO FOREIGN KEY(BUS_NO) REFERENCES BUSINESS_TB(BUS_NO);
ALTER TABLE SERVICE_TB ADD CONSTRAINT FK_SVC_BCT_CODE FOREIGN KEY(BCT_CODE) REFERENCES BUS_CATEGORY_TB(BCT_CODE);
ALTER TABLE SERVICE_TB ADD CONSTRAINT PK_SVC_TB PRIMARY KEY(BUS_NO, BCT_CODE);

DROP SYNONYM SVC;
CREATE SYNONYM SVC FOR SERVICE_TB;


-- 해시 태그 테이블 (TAG)

DROP TABLE HASHTAG_TB CASCADE CONSTRAINTS;
CREATE TABLE HASHTAG_TB (
    TAG_NO      NCHAR(8),     -- PK
    TAG_NAME    NVARCHAR2(30) NOT NULL  -- UNIQUE
);

ALTER TABLE HASHTAG_TB ADD CONSTRAINT PK_TAG_TB PRIMARY KEY(TAG_NO);
ALTER TABLE HASHTAG_TB ADD CONSTRAINT UQ_TAG_NAME UNIQUE(TAG_NAME);

DROP SYNONYM TAG;
CREATE SYNONYM TAG FOR HASHTAG_TB;

DROP SEQUENCE TAG_SEQ;
CREATE SEQUENCE TAG_SEQ START WITH 1000001 INCREMENT BY 1 MAXVALUE 9999999;


-- 기업 해시 태그 테이블 (BTG)

DROP TABLE BUS_HASHTAG_TB CASCADE CONSTRAINTS;
CREATE TABLE BUS_HASHTAG_TB (
    BUS_NO      NCHAR(8),   -- PK, FK
    BCT_CODE    NCHAR(1),   -- PK, FK
    TAG_NO      NCHAR(8)    -- PK, FK
);

ALTER TABLE BUS_HASHTAG_TB ADD CONSTRAINT FK_BTG_BUS_NO FOREIGN KEY(BUS_NO) REFERENCES BUSINESS_TB(BUS_NO);
ALTER TABLE BUS_HASHTAG_TB ADD CONSTRAINT FK_BTG_BCT_CODE FOREIGN KEY(BCT_CODE) REFERENCES BUS_CATEGORY_TB(BCT_CODE);
ALTER TABLE BUS_HASHTAG_TB ADD CONSTRAINT FK_BTG_TAG_NO FOREIGN KEY(TAG_NO) REFERENCES HASHTAG_TB(TAG_NO);
ALTER TABLE BUS_HASHTAG_TB ADD CONSTRAINT PK_BTG_TB PRIMARY KEY(BUS_NO, BCT_CODE, TAG_NO);

DROP SYNONYM BTG;
CREATE SYNONYM BTG FOR BUS_HASHTAG_TB;


-- 경고 종류 테이블 (OUT)

DROP TABLE OUT_CATEGORY_TB CASCADE CONSTRAINTS;
CREATE TABLE OUT_CATEGORY_TB (
    OUT_NO      NUMBER(2, 0),   -- PK
    OUT_NAME    NVARCHAR2(10)   NOT NULL    -- UNIQUE
);

ALTER TABLE OUT_CATEGORY_TB ADD CONSTRAINT PK_OUT_TB PRIMARY KEY(OUT_NO);
ALTER TABLE OUT_CATEGORY_TB ADD CONSTRAINT UQ_OUT_NAME UNIQUE(OUT_NAME);

DROP SYNONYM OUT;
CREATE SYNONYM OUT FOR OUT_CATEGORY_TB;

DROP SEQUENCE OUT_SEQ;
CREATE SEQUENCE OUT_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE 99;

INSERT INTO OUT VALUES(OUT_SEQ.NEXTVAL, '노쇼');
INSERT INTO OUT VALUES(OUT_SEQ.NEXTVAL, '경고');
INSERT INTO OUT VALUES(OUT_SEQ.NEXTVAL, '정지');
INSERT INTO OUT VALUES(OUT_SEQ.NEXTVAL, '경고해제');
INSERT INTO OUT VALUES(OUT_SEQ.NEXTVAL, '정지해제');


-- 블랙리스트 테이블 (BLK)

DROP TABLE BLACKLIST_TB CASCADE CONSTRAINTS;
CREATE TABLE BLACKLIST_TB (
    PER_NO      NCHAR(8),                       -- PK, FK
    OUT_NO      NUMBER(2, 0),                   -- PK, FK
    BLK_TIME    DATE            DEFAULT SYSDATE -- PK
);

ALTER TABLE BLACKLIST_TB ADD CONSTRAINT FK_BLK_PER_NO FOREIGN KEY(PER_NO) REFERENCES PERSONAL_TB(PER_NO);
ALTER TABLE BLACKLIST_TB ADD CONSTRAINT FK_BLK_OUT_NO FOREIGN KEY(OUT_NO) REFERENCES OUT_CATEGORY_TB(OUT_NO);
ALTER TABLE BLACKLIST_TB ADD CONSTRAINT PK_BLK_TB PRIMARY KEY(PER_NO, OUT_NO, BLK_TIME);

DROP SYNONYM BLK;
CREATE SYNONYM BLK FOR BLACKLIST_TB;


-- 기업 고정 스케줄 테이블 (BFX)

DROP TABLE BUS_FIXED_TB CASCADE CONSTRAINTS;
CREATE TABLE BUS_FIXED_TB (
    BUS_NO      NCHAR(8),   -- PK, FK
    BCT_CODE    NCHAR(1),   -- PK, FK
    BFX_MON     NCHAR(8)    DEFAULT 'XXXXXXXX',
    BFX_TUE     NCHAR(8)    DEFAULT 'XXXXXXXX',
    BFX_WED     NCHAR(8)    DEFAULT 'XXXXXXXX',
    BFX_THU     NCHAR(8)    DEFAULT 'XXXXXXXX',
    BFX_FRI     NCHAR(8)    DEFAULT 'XXXXXXXX',
    BFX_SAT     NCHAR(8)    DEFAULT 'XXXXXXXX',
    BFX_SUN     NCHAR(8)    DEFAULT 'XXXXXXXX',
    BFX_HLD     NCHAR(8)    DEFAULT 'XXXXXXXX',
    BFX_LCH     NCHAR(8)    DEFAULT 'XXXXXXXX'
);

ALTER TABLE BUS_FIXED_TB ADD CONSTRAINT FK_BFX_BUS_NO FOREIGN KEY(BUS_NO) REFERENCES BUSINESS_TB(BUS_NO);
ALTER TABLE BUS_FIXED_TB ADD CONSTRAINT FK_BFX_BCT_CODE FOREIGN KEY(BCT_CODE) REFERENCES BUS_CATEGORY_TB(BCT_CODE);
ALTER TABLE BUS_FIXED_TB ADD CONSTRAINT PK_BFX_TB PRIMARY KEY(BUS_NO, BCT_CODE);

DROP SYNONYM BFX;
CREATE SYNONYM BFX FOR BUS_FIXED_TB;


-- 기업 스케줄 테이블 (BSD)

DROP TABLE BUS_SCHEDULE_TB CASCADE CONSTRAINTS;
CREATE TABLE BUS_SCHEDULE_TB (
    BUS_NO      NCHAR(8),   -- PK, FK
    BCT_CODE    NCHAR(1),   -- PK, FK
    BSD_DATE    DATE,       -- PK
    AM_OPEN     NCHAR(4)    DEFAULT 'XXXX',
    AM_CLOSE    NCHAR(4)    DEFAULT 'XXXX',
    PM_OPEN     NCHAR(4)    DEFAULT 'XXXX',
    PM_CLOSE    NCHAR(4)    DEFAULT 'XXXX'
);

ALTER TABLE BUS_SCHEDULE_TB ADD CONSTRAINT FK_BSD_BUS_NO FOREIGN KEY(BUS_NO) REFERENCES BUSINESS_TB(BUS_NO);
ALTER TABLE BUS_SCHEDULE_TB ADD CONSTRAINT FK_BSD_BCT_CODE FOREIGN KEY(BCT_CODE) REFERENCES BUS_CATEGORY_TB(BCT_CODE);
ALTER TABLE BUS_SCHEDULE_TB ADD CONSTRAINT PK_BSD_TB PRIMARY KEY(BUS_NO, BCT_CODE, BSD_DATE);

DROP SYNONYM BSD;
CREATE SYNONYM BSD FOR BUS_SCHEDULE_TB;


-- 메뉴 테이블 (MENU)

DROP TABLE MENU_TB CASCADE CONSTRAINTS;
CREATE TABLE MENU_TB (
    MENU_NO     NUMBER(2, 0),   -- PK
    BCT_CODE    NCHAR(1),       -- FK
    MENU_NAME   NVARCHAR2(20)   NOT NULL
);

ALTER TABLE MENU_TB ADD CONSTRAINT PK_MENU_TB PRIMARY KEY(MENU_NO);
ALTER TABLE MENU_TB ADD CONSTRAINT FK_MENU_BCT_CODE FOREIGN KEY(BCT_CODE) REFERENCES BUS_CATEGORY_TB(BCT_CODE);

DROP SYNONYM MENU;
CREATE SYNONYM MENU FOR MENU_TB;

DROP SEQUENCE MENU_SEQ;
CREATE SEQUENCE MENU_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE 99;

INSERT INTO MENU VALUES(MENU_SEQ.NEXTVAL, 'B', '가위컷');
INSERT INTO MENU VALUES(MENU_SEQ.NEXTVAL, 'B', '목욕');
INSERT INTO MENU VALUES(MENU_SEQ.NEXTVAL, 'B', '전체컷');
INSERT INTO MENU VALUES(MENU_SEQ.NEXTVAL, 'B', '염색');
INSERT INTO MENU VALUES(MENU_SEQ.NEXTVAL, 'B', '부분컷');
INSERT INTO MENU VALUES(MENU_SEQ.NEXTVAL, 'H', '1박');
INSERT INTO MENU VALUES(MENU_SEQ.NEXTVAL, 'B', '고양이무마취');
INSERT INTO MENU VALUES(MENU_SEQ.NEXTVAL, 'H', '약 투여');
INSERT INTO MENU VALUES(MENU_SEQ.NEXTVAL, 'H', '산책');
INSERT INTO MENU VALUES(MENU_SEQ.NEXTVAL, 'H', '간식');
INSERT INTO MENU VALUES(MENU_SEQ.NEXTVAL, 'B', '귀 청소');
INSERT INTO MENU VALUES(MENU_SEQ.NEXTVAL, 'B', '발톱깎기');
INSERT INTO MENU VALUES(MENU_SEQ.NEXTVAL, 'M', '진료');
INSERT INTO MENU VALUES(MENU_SEQ.NEXTVAL, 'M', '수술');
INSERT INTO MENU VALUES(MENU_SEQ.NEXTVAL, 'M', '치과');
INSERT INTO MENU VALUES(MENU_SEQ.NEXTVAL, 'H', '목욕');


-- 가격 테이블 (PRC)

DROP TABLE PRICE_TB CASCADE CONSTRAINTS;
CREATE TABLE PRICE_TB (
    BUS_NO      NCHAR(8),       -- PK, FK
    BCT_CODE    NCHAR(1),       -- PK, FK
    MENU_NO     NUMBER(2, 0),   -- PK, FK
    PTY_NO      NUMBER(2, 0),   -- PK, FK
    PRICE       NVARCHAR2(7)    DEFAULT '0'
);

ALTER TABLE PRICE_TB ADD CONSTRAINT FK_PRC_BUS_NO FOREIGN KEY(BUS_NO) REFERENCES BUSINESS_TB(BUS_NO);
ALTER TABLE PRICE_TB ADD CONSTRAINT FK_PRC_BCT_CODE FOREIGN KEY(BCT_CODE) REFERENCES BUS_CATEGORY_TB(BCT_CODE);
ALTER TABLE PRICE_TB ADD CONSTRAINT FK_PRC_MENU_NO FOREIGN KEY(MENU_NO) REFERENCES MENU_TB(MENU_NO);
ALTER TABLE PRICE_TB ADD CONSTRAINT FK_PRC_PTY_NO FOREIGN KEY(PTY_NO) REFERENCES PET_TYPE_TB(PTY_NO);
ALTER TABLE PRICE_TB ADD CONSTRAINT PK_PRC_TB PRIMARY KEY(BUS_NO, BCT_CODE, MENU_NO, PTY_NO);

DROP SYNONYM PRC;
CREATE SYNONYM PRC FOR PRICE_TB;


-- 직원 테이블 (EMP)

DROP TABLE EMPLOYEE_TB CASCADE CONSTRAINTS;
CREATE TABLE EMPLOYEE_TB (
    EMP_NO      NCHAR(8),       -- PK
    BUS_NO      NCHAR(8),       -- FK
    BCT_CODE    NCHAR(1),       -- FK
    EMP_NAME    NVARCHAR2(20)   NOT NULL,
    EMP_POS     NVARCHAR2(10)   NOT NULL,
    EMP_PART    NVARCHAR2(100),
    EMP_PHOTO   NVARCHAR2(1000) DEFAULT 'user.png',
    EMP_LOC     NVARCHAR2(1000) DEFAULT 'resources/images/defaultProfile/',
    EMP_LICENSE NVARCHAR2(1000) NOT NULL,
    EMP_LCLOC   NVARCHAR2(1000) NOT NULL,
    EMP_CHK     NCHAR(1)        DEFAULT 'X',    -- CHECK('O', 'X')
    EMP_TIME    DATE            DEFAULT SYSDATE
);

ALTER TABLE EMPLOYEE_TB ADD CONSTRAINT FK_EMP_BUS_NO FOREIGN KEY(BUS_NO) REFERENCES BUSINESS_TB(BUS_NO);
ALTER TABLE EMPLOYEE_TB ADD CONSTRAINT FK_EMP_BCT_CODE FOREIGN KEY(BCT_CODE) REFERENCES BUS_CATEGORY_TB(BCT_CODE);
ALTER TABLE EMPLOYEE_TB ADD CONSTRAINT PK_EMP_TB PRIMARY KEY(EMP_NO);
ALTER TABLE EMPLOYEE_TB ADD CONSTRAINT CH_EMP_CHK CHECK(EMP_CHK IN ('O', 'X'));

DROP SYNONYM EMP;
CREATE SYNONYM EMP FOR EMPLOYEE_TB;

DROP SEQUENCE EMP_SEQ;
CREATE SEQUENCE EMP_SEQ START WITH 1000001 INCREMENT BY 1 MAXVALUE 9999999;


-- 직원 고정 스케줄 테이블 (EFX)

DROP TABLE EMP_FIXED_TB CASCADE CONSTRAINTS;
CREATE TABLE EMP_FIXED_TB (
    EMP_NO  NCHAR(8),   -- PK, FK
    EFX_MON NCHAR(8)    DEFAULT 'XXXXXXXX',
    EFX_TUE NCHAR(8)    DEFAULT 'XXXXXXXX',
    EFX_WED NCHAR(8)    DEFAULT 'XXXXXXXX',
    EFX_THU NCHAR(8)    DEFAULT 'XXXXXXXX',
    EFX_FRI NCHAR(8)    DEFAULT 'XXXXXXXX',
    EFX_SAT NCHAR(8)    DEFAULT 'XXXXXXXX',
    EFX_SUN NCHAR(8)    DEFAULT 'XXXXXXXX',
    EFX_HLD NCHAR(8)    DEFAULT 'XXXXXXXX',
    EFX_LCH NCHAR(8)    DEFAULT 'XXXXXXXX'
);

ALTER TABLE EMP_FIXED_TB ADD CONSTRAINT FK_EFX_EMP_NO FOREIGN KEY(EMP_NO) REFERENCES EMPLOYEE_TB(EMP_NO);
ALTER TABLE EMP_FIXED_TB ADD CONSTRAINT PK_EFX_TB PRIMARY KEY(EMP_NO);

DROP SYNONYM EFX;
CREATE SYNONYM EFX FOR EMP_FIXED_TB;


-- 직원 스케줄 테이블 (ESD)

DROP TABLE EMP_SCHEDULE_TB CASCADE CONSTRAINTS;
CREATE TABLE EMP_SCHEDULE_TB (
    EMP_NO      NCHAR(8),   -- PK, FK
    ESD_DATE    DATE,       -- PK
    AM_OPEN     NCHAR(4)    DEFAULT 'XXXX',
    AM_CLOSE    NCHAR(4)    DEFAULT 'XXXX',
    PM_OPEN     NCHAR(4)    DEFAULT 'XXXX',
    PM_CLOSE    NCHAR(4)    DEFAULT 'XXXX'
);

ALTER TABLE EMP_SCHEDULE_TB ADD CONSTRAINT FK_ESD_EMP_NO FOREIGN KEY(EMP_NO) REFERENCES EMPLOYEE_TB(EMP_NO);
ALTER TABLE EMP_SCHEDULE_TB ADD CONSTRAINT PK_ESD_TB PRIMARY KEY(EMP_NO, ESD_DATE);

DROP SYNONYM ESD;
CREATE SYNONYM ESD FOR EMP_SCHEDULE_TB;


-- 예약 테이블 (BK)

DROP TABLE BOOKING_TB CASCADE CONSTRAINTS;
CREATE TABLE BOOKING_TB (
    BK_NO       NCHAR(8),       -- PK
    PER_NO      NCHAR(8),       -- FK
    PET_NO      NCHAR(8),       -- FK
    BUS_NO      NCHAR(8),       -- FK
    BCT_CODE    NCHAR(1),       -- FK
    EMP_NO      NCHAR(8),       -- FK
    BK_TIME     DATE            DEFAULT SYSDATE,
    BK_PAY      NUMBER(7, 0)    DEFAULT 0,
    VS_START    DATE            NOT NULL,
    VS_END      DATE            NOT NULL,
    BK_CMT      NVARCHAR2(500),
    BK_CHK      NCHAR(2)        DEFAULT '신청', -- CHECK('신청', '취소', '승인', '거절')
    VS_CHK      NCHAR(1)        DEFAULT 'X',    -- CHECK('O', 'X')
    BK_REJMSG   NVARCHAR2(300)
);

ALTER TABLE BOOKING_TB ADD CONSTRAINT FK_BK_PER_NO FOREIGN KEY(PER_NO) REFERENCES PERSONAL_TB(PER_NO);
ALTER TABLE BOOKING_TB ADD CONSTRAINT FK_BK_PET_NO FOREIGN KEY(PET_NO) REFERENCES PET_TB(PET_NO);
ALTER TABLE BOOKING_TB ADD CONSTRAINT FK_BK_BUS_NO FOREIGN KEY(BUS_NO) REFERENCES BUSINESS_TB(BUS_NO);
ALTER TABLE BOOKING_TB ADD CONSTRAINT FK_BK_BCT_CODE FOREIGN KEY(BCT_CODE) REFERENCES BUS_CATEGORY_TB(BCT_CODE);
ALTER TABLE BOOKING_TB ADD CONSTRAINT FK_BK_EMP_NO FOREIGN KEY(EMP_NO) REFERENCES EMPLOYEE_TB(EMP_NO);
ALTER TABLE BOOKING_TB ADD CONSTRAINT PK_BK_TB PRIMARY KEY(BK_NO);
ALTER TABLE BOOKING_TB ADD CONSTRAINT CH_BK_CHK CHECK(BK_CHK IN('신청', '취소', '승인', '거절'));
ALTER TABLE BOOKING_TB ADD CONSTRAINT CH_VS_CHK CHECK(VS_CHK IN('O', 'X'));

DROP SYNONYM BK;
CREATE SYNONYM BK FOR BOOKING_TB;

DROP SEQUENCE BK_SEQ;
CREATE SEQUENCE BK_SEQ START WITH 1000001 INCREMENT BY 1 MAXVALUE 9999999;


-- 예약 메뉴 테이블 (BKM)

DROP TABLE BK_MENU_TB CASCADE CONSTRAINTS;
CREATE TABLE BK_MENU_TB (
    BK_NO   NCHAR(8),       -- PK, FK
    MENU_NO NUMBER(2, 0)    -- PK, FK
);

ALTER TABLE BK_MENU_TB ADD CONSTRAINT FK_BKM_BK_NO FOREIGN KEY(BK_NO) REFERENCES BOOKING_TB(BK_NO);
ALTER TABLE BK_MENU_TB ADD CONSTRAINT FK_BKM_MENU_NO FOREIGN KEY(MENU_NO) REFERENCES MENU_TB(MENU_NO);
ALTER TABLE BK_MENU_TB ADD CONSTRAINT PK_BKM_TB PRIMARY KEY(BK_NO, MENU_NO);

DROP SYNONYM BKM;
CREATE SYNONYM BKM FOR BK_MENU_TB;


-- 결제 테이블 (PM)

DROP TABLE PAYMENT_TB CASCADE CONSTRAINTS;
CREATE TABLE PAYMENT_TB (
    BK_NO       NCHAR(8),       -- PK, FK
    PM_PRICE    NUMBER(7, 0)    NOT NULL,
    PM_TIME     DATE            DEFAULT SYSDATE,
    PM_WAY      NVARCHAR2(10)   NOT NULL
);

ALTER TABLE PAYMENT_TB ADD CONSTRAINT FK_PM_BK_NO FOREIGN KEY(BK_NO) REFERENCES BOOKING_TB(BK_NO);
ALTER TABLE PAYMENT_TB ADD CONSTRAINT PK_PM_TB PRIMARY KEY(BK_NO);

DROP SYNONYM PM;
CREATE SYNONYM PM FOR PAYMENT_TB;


-- 취소 수수료 테이블 (CAR)

DROP TABLE CANCEL_CHARGE_TB CASCADE CONSTRAINTS;
CREATE TABLE CANCEL_CHARGE_TB (
    CAR_DAY NUMBER(1, 0),   -- PK
    CAR_CRG NUMBER          NOT NULL    -- UNIQUE
);

ALTER TABLE CANCEL_CHARGE_TB ADD CONSTRAINT PK_CAR_TB PRIMARY KEY(CAR_DAY);
ALTER TABLE CANCEL_CHARGE_TB ADD CONSTRAINT UQ_CAR_CRG UNIQUE(CAR_CRG);

DROP SYNONYM CAR;
CREATE SYNONYM CAR FOR CANCEL_CHARGE_TB;

INSERT INTO CAR VALUES(3, 1);
INSERT INTO CAR VALUES(2, 0.8);
INSERT INTO CAR VALUES(1, 0.5);


-- 예약 취소 테이블 (CAN)

DROP TABLE CANCEL_TB CASCADE CONSTRAINTS;
CREATE TABLE CANCEL_TB (
    BK_NO       NCHAR(8),   -- PK, FK
    CAN_TIME    DATE        DEFAULT SYSDATE,
    CAR_CRG     NUMBER      DEFAULT 1           -- FK
);

ALTER TABLE CANCEL_TB ADD CONSTRAINT FK_CAN_BK_NO FOREIGN KEY(BK_NO) REFERENCES BOOKING_TB(BK_NO);
ALTER TABLE CANCEL_TB ADD CONSTRAINT FK_CAN_CAR_CRG FOREIGN KEY(CAR_CRG) REFERENCES CANCEL_CHARGE_TB(CAR_CRG);
ALTER TABLE CANCEL_TB ADD CONSTRAINT PK_CAN_TB PRIMARY KEY(BK_NO);

DROP SYNONYM CAN;
CREATE SYNONYM CAN FOR CANCEL_TB;


-- 리뷰 테이블 (REV)

DROP TABLE REVIEW_TB CASCADE CONSTRAINTS;
CREATE TABLE REVIEW_TB (
    BK_NO       NCHAR(8),       -- PK, FK
    BUS_NO      NCHAR(8),       -- PK, FK
    BCT_CODE    NCHAR(1),       -- PK, FK
    PER_NO      NCHAR(8),       -- PK, FK
    REV_STAR    NUMBER(3, 0)    NOT NULL,
    REV_CMT     NVARCHAR2(500)
);

ALTER TABLE REVIEW_TB ADD CONSTRAINT FK_REV_BK_NO FOREIGN KEY(BK_NO) REFERENCES BOOKING_TB(BK_NO);
ALTER TABLE REVIEW_TB ADD CONSTRAINT FK_REV_BUS_NO FOREIGN KEY(BUS_NO) REFERENCES BUSINESS_TB(BUS_NO);
ALTER TABLE REVIEW_TB ADD CONSTRAINT FK_REV_BCT_CODE FOREIGN KEY(BCT_CODE) REFERENCES BUS_CATEGORY_TB(BCT_CODE);
ALTER TABLE REVIEW_TB ADD CONSTRAINT FK_REV_PER_NO FOREIGN KEY(PER_NO) REFERENCES PERSONAL_TB(PER_NO);
ALTER TABLE REVIEW_TB ADD CONSTRAINT PK_REV_TB PRIMARY KEY(BK_NO, BUS_NO, BCT_CODE, PER_NO);

DROP SYNONYM REV;
CREATE SYNONYM REV FOR REVIEW_TB;


-- 즐겨찾기 테이블 (FAV)

DROP TABLE FAVORITE_TB CASCADE CONSTRAINTS;
CREATE TABLE FAVORITE_TB (
    PER_NO  NCHAR(8),   -- PK, FK
    BUS_NO  NCHAR(8)    -- PK, FK
);

ALTER TABLE FAVORITE_TB ADD CONSTRAINT FK_FAV_PER_NO FOREIGN KEY(PER_NO) REFERENCES PERSONAL_TB(PER_NO);
ALTER TABLE FAVORITE_TB ADD CONSTRAINT FK_FAV_BUS_NO FOREIGN KEY(BUS_NO) REFERENCES BUSINESS_TB(BUS_NO);
ALTER TABLE FAVORITE_TB ADD CONSTRAINT PK_FAV_TB PRIMARY KEY(PER_NO, BUS_NO);

DROP SYNONYM FAV;
CREATE SYNONYM FAV FOR FAVORITE_TB;


-- 기업 게시판 카테고리 테이블 (BBC)

DROP TABLE BUS_BOARD_CATEGORY_TB CASCADE CONSTRAINTS;
CREATE TABLE BUS_BOARD_CATEGORY_TB (
    BBC_NO      NUMBER(2, 0),   -- PK
    BBC_NAME    NVARCHAR2(10)   NOT NULL    -- UNIQUE
);

ALTER TABLE BUS_BOARD_CATEGORY_TB ADD CONSTRAINT PK_BBC_TB PRIMARY KEY(BBC_NO);
ALTER TABLE BUS_BOARD_CATEGORY_TB ADD CONSTRAINT QU_BBC_NAME UNIQUE(BBC_NAME);

DROP SYNONYM BBC;
CREATE SYNONYM BBC FOR BUS_BOARD_CATEGORY_TB;

DROP SEQUENCE BBC_SEQ;
CREATE SEQUENCE BBC_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE 99;

INSERT INTO BBC VALUES(BBC_SEQ.NEXTVAL, '공지사항');
INSERT INTO BBC VALUES(BBC_SEQ.NEXTVAL, '이벤트');


-- 기업 게시판 테이블 (BBO)

DROP TABLE BUS_BOARD_TB CASCADE CONSTRAINTS;
CREATE TABLE BUS_BOARD_TB (
    BBO_NO      NUMBER,         -- PK
    BUS_NO      NCHAR(8),       -- FK
    BCT_CODE    NCHAR(1),       -- FK
    BBC_NO      NUMBER(2, 0),   -- FK
    BBO_TITLE   NVARCHAR2(50)   NOT NULL,
    BBO_CTT     NCLOB           NOT NULL,
    BBO_DATE    DATE            DEFAULT SYSDATE
);

ALTER TABLE BUS_BOARD_TB ADD CONSTRAINT FK_BBO_BUS_NO FOREIGN KEY(BUS_NO) REFERENCES BUSINESS_TB(BUS_NO);
ALTER TABLE BUS_BOARD_TB ADD CONSTRAINT FK_BBO_BCT_CODE FOREIGN KEY(BCT_CODE) REFERENCES BUS_CATEGORY_TB(BCT_CODE);
ALTER TABLE BUS_BOARD_TB ADD CONSTRAINT FK_BBO_BBC_NO FOREIGN KEY(BBC_NO) REFERENCES BUS_BOARD_CATEGORY_TB(BBC_NO);
ALTER TABLE BUS_BOARD_TB ADD CONSTRAINT PK_BBO_TB PRIMARY KEY(BBO_NO);

DROP SYNONYM BBO;
CREATE SYNONYM BBO FOR BUS_BOARD_TB;

DROP SEQUENCE BBO_SEQ;
CREATE SEQUENCE BBO_SEQ START WITH 1 INCREMENT BY 1;


-- 관리자 게시판 카테고리 테이블 (ABC)

DROP TABLE ADM_BOARD_CATEGORY_TB CASCADE CONSTRAINTS;
CREATE TABLE ADM_BOARD_CATEGORY_TB (
    ABC_NO      NUMBER(2, 0),   -- PK
    ABC_NAME    NVARCHAR2(10)   NOT NULL    -- UNIQUE
);

ALTER TABLE ADM_BOARD_CATEGORY_TB ADD CONSTRAINT PK_ABC_TB PRIMARY KEY(ABC_NO);
ALTER TABLE ADM_BOARD_CATEGORY_TB ADD CONSTRAINT UQ_ABC_NAME UNIQUE(ABC_NAME);

DROP SYNONYM ABC;
CREATE SYNONYM ABC FOR ADM_BOARD_CATEGORY_TB;

DROP SEQUENCE ABC_SEQ;
CREATE SEQUENCE ABC_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE 99;

INSERT INTO ABC VALUES(ABC_SEQ.NEXTVAL, '개인');
INSERT INTO ABC VALUES(ABC_SEQ.NEXTVAL, '기업');


-- 관리자 게시판 테이블 (ABO)

DROP TABLE ADM_BOARD_TB CASCADE CONSTRAINTS;
CREATE TABLE ADM_BOARD_TB (
    ABO_NO      NUMBER,         -- PK
    ABC_NO      NUMBER(2, 0),   -- FK
    ABO_TITLE   NVARCHAR2(50)   NOT NULL,
    ABO_CTT     NCLOB           NOT NULL,
    ABO_DATE    DATE            DEFAULT SYSDATE
);

ALTER TABLE ADM_BOARD_TB ADD CONSTRAINT FK_ABO_ABC_NO FOREIGN KEY(ABC_NO) REFERENCES ADM_BOARD_CATEGORY_TB(ABC_NO);
ALTER TABLE ADM_BOARD_TB ADD CONSTRAINT PK_ABO_TB PRIMARY KEY(ABO_NO);

DROP SYNONYM ABO;
CREATE SYNONYM ABO FOR ADM_BOARD_TB;

DROP SEQUENCE ABO_SEQ;
CREATE SEQUENCE ABO_SEQ START WITH 1 INCREMENT BY 1;